# Generated by Django 2.2.1 on 2019-05-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allobservations',
            name='ptype',
            field=models.CharField(choices=[('Application Security', 'Application Security'), ('Network Review', 'Network Review')], default='Application Security', max_length=20),
        ),
    ]
