# Generated by Django 2.1.7 on 2019-06-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190508_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allobservations',
            name='ptype',
            field=models.CharField(choices=[('Application Security', 'Application Security'), ('Network Review', 'Network Review'), ('Vulnerability Assessment', 'Vulnerability Assessment'), ('Mobile Security', 'Mobile Security')], default='Application Security', max_length=20),
        ),
    ]
