# Generated by Django 3.0.8 on 2020-07-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190614_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allobservations',
            name='ptype',
            field=models.CharField(choices=[('Application Security', 'Application Security'), ('Network Architecture Review', 'Network Architecture Review'), ('Vulnerability Assessment', 'Vulnerability Assessment'), ('Mobile Application Security', 'Mobile Application Security')], default='Application Security', max_length=40),
        ),
    ]
